# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tum.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QMenu, QAction, QVBoxLayout, QHBoxLayout, QLabel, QCheckBox, QLineEdit, QSizePolicy, QSpacerItem, QWidget
from PyQt5.QtGui import QIcon, QValidator
import yaml

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowTitle("CBRChipCalc")
        MainWindow.setWindowIcon(QIcon('icon/2857379.png'))
        MainWindow.resize(1061, 749)
        self.load_config_cbr()
        self.number_stt = 0
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.check_state = {}
       #region setupUi
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 25))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.path_file = QtWidgets.QTextEdit(self.widget)
        self.path_file.setMinimumSize(QtCore.QSize(0, 25))
        self.path_file.setMaximumSize(QtCore.QSize(16777215, 25))
        self.path_file.setObjectName("path_file")
        self.horizontalLayout_3.addWidget(self.path_file)
        self.btn_open_file = QtWidgets.QToolButton(self.widget)
        self.btn_open_file.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_open_file.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_open_file.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/8725795_folder_open_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_open_file.setIcon(icon)
        self.btn_open_file.setIconSize(QtCore.QSize(20, 20))
        self.btn_open_file.setObjectName("btn_open_file")
        self.horizontalLayout_3.addWidget(self.btn_open_file)
        self.verticalLayout_7.addWidget(self.widget)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.dda = QtWidgets.QVBoxLayout()
        self.dda.setObjectName("dda")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 0, 0))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        # self.verticalLayout_3.setSpacing(0)

        self.scrollArea.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.scrollArea.customContextMenuRequested.connect(self.show_context_menu_sub)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.dda.addWidget(self.scrollArea)

        self.horizontalLayout_10.addLayout(self.dda)
        self.verticalWidget = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_row_select = QtWidgets.QLabel(self.groupBox_2)
        self.label_row_select.value = None
        self.label_row_select.setObjectName("label_row_select")
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        # font.setItalic(True)
        self.label_row_select.setFont(font)
        self.verticalLayout_10.addWidget(self.label_row_select)
        self.btn_data_processing = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_data_processing.setObjectName("btn_data_processing")
        self.verticalLayout_10.addWidget(self.btn_data_processing)
        self.widget_7 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.label_12 = QtWidgets.QLabel(self.widget_7)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.comboBox_label = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_label.setObjectName("comboBox_label")
        self.horizontalLayout_9.addWidget(self.comboBox_label)
        self.verticalLayout_10.addWidget(self.widget_7)
        self.btn_autolabel = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_autolabel.setObjectName("btn_autolabel")
        self.verticalLayout_10.addWidget(self.btn_autolabel)
        self.btn_calculate_12 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_calculate_12.setObjectName("btn_calculate_12")
        self.verticalLayout_10.addWidget(self.btn_calculate_12)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_10.addWidget(self.verticalWidget)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.comboBox_label2 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_label2.setObjectName("comboBox_label2")
        self.comboBox_label2.addItems(self.config['program']['data'])
        self.comboBox_label2.currentTextChanged.connect(lambda x: self.load_params())
        self.horizontalLayout_4.addWidget(self.comboBox_label2)
        self.verticalLayout.addWidget(self.widget_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 383, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_3.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_3.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout.addWidget(self.scrollArea_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.widget1 = QtWidgets.QWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setMinimumSize(QtCore.QSize(300, 0))
        self.widget1.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.widget1)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.edt_k = QtWidgets.QLineEdit(self.groupBox)
        self.edt_k.setText('400')
        self.edt_k.setObjectName("edt_k")
        self.edt_k.setValidator(NumberValidator())
        self.gridLayout.addWidget(self.edt_k, 0, 1, 1, 1)
        self.edt_n = QtWidgets.QLineEdit(self.groupBox)
        self.edt_n.setText('5')
        self.edt_n.setObjectName("edt_n")
        self.edt_n.setValidator(NumberValidator())
        self.gridLayout.addWidget(self.edt_n, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btn_data_processing2 = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_data_processing2.setObjectName("btn_data_processing2")
        self.verticalLayout_11.addWidget(self.btn_data_processing2)

        self.btn_calculate2 = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_calculate2.setObjectName("btn_calculate2")

        self.verticalLayout_11.addWidget(self.btn_calculate2)
        self.verticalLayout_4.addWidget(self.groupBox_4)

        self.widget_3 = QtWidgets.QWidget(self.widget1)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.verticalLayout_4.addWidget(self.widget_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_5.addWidget(self.widget1)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox_3)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.log_programs = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.log_programs.setSizePolicy(sizePolicy)
        self.log_programs.setGeometry(QtCore.QRect(0, 0, 296, 714))
        self.log_programs.setObjectName("log_programs")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.log_programs)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea_2.setWidget(self.log_programs)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
       #endregion 

        self.add_tille_data()
        self.btn_data_processing2.clicked.connect(lambda x: self.procesing_data_form2())
        
    
    def load_config_cbr(self):
        with open('src/config.yaml', 'r', encoding='utf-8') as file:
            self.config = yaml.safe_load(file)

    #region form 1
    def get_line_edit_select(self):
        checkbox_select = None
        checkboxes = self.scrollAreaWidgetContents.findChildren(QtWidgets.QCheckBox, QtCore.QRegExp("checkbox.*"))
        for checkbox in checkboxes:
            if checkbox.isChecked():
                checkbox_select = checkbox
                break
        if checkbox_select is None: 
            return None
        wiget =checkbox_select.parent()
        values = []
        for i, value in enumerate(self.config['program']['values']):
            lineEdit = wiget.findChild(QtWidgets.QLineEdit, f"lineEdit_{i}")
            values.append((value, lineEdit))
        return values
    def add_tille_data(self):
        widget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(widget_5.sizePolicy().hasHeightForWidth())
        widget_5.setSizePolicy(sizePolicy)
        widget_5.setObjectName("widget_5")
        horizontalLayout_8 = QtWidgets.QHBoxLayout(widget_5)
        horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        horizontalLayout_8.setObjectName("horizontalLayout_8")
        label_14 = QtWidgets.QLabel(widget_5)
        label_14.setMinimumSize(QtCore.QSize(40, 0))
        label_14.setMaximumSize(QtCore.QSize(40, 16777215))
        label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        label_14.setText('No.')
        
        horizontalLayout_8.addWidget(label_14)
        label_13 = QtWidgets.QLabel(widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(label_13.sizePolicy().hasHeightForWidth())
        label_13.setSizePolicy(sizePolicy)
        label_13.setMinimumSize(QtCore.QSize(50, 0))
        label_13.setMaximumSize(QtCore.QSize(50, 16777215))
        label_13.setText("Select")
        horizontalLayout_8.addWidget(label_13)
        
        for i, value in enumerate(self.config['program']['values']):
            label_10 = QtWidgets.QLabel(widget_5)
            label_10.setMinimumSize(QtCore.QSize(100, 0))
            label_10.setMaximumSize(QtCore.QSize(100, 16777215))
            label_10.setAlignment(QtCore.Qt.AlignCenter)
            label_10.setText(value)
            horizontalLayout_8.addWidget(label_10)
        
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_3.addWidget(widget_5)
        line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        line.setFrameShape(QtWidgets.QFrame.HLine)
        line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalLayout_3.addWidget(line)
        #region xử lý action table form 1
    def add_row_value(self):
        self.number_stt += 1
        widget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        widget_6.setContentsMargins(0, 6, 0, 0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(widget_6.sizePolicy().hasHeightForWidth())
        widget_6.setSizePolicy(sizePolicy)
        widget_6.setObjectName("widget_6")

        layout = QtWidgets.QVBoxLayout(widget_6)
        layout.setContentsMargins(0, 0, 0, 0)
        horizontalLayout = QtWidgets.QHBoxLayout()
        horizontalLayout.setContentsMargins(0, 0, 0, 0)
        horizontalLayout.setObjectName("horizontalLayout")
        label_15 = QtWidgets.QLabel(widget_6)
        label_15.value = self.number_stt
        label_15.setMinimumSize(QtCore.QSize(40, 0))
        label_15.setMaximumSize(QtCore.QSize(40, 16777215))
        label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        label_15.setText(str(self.number_stt))
        label_15.setObjectName("label_15")
        horizontalLayout.addWidget(label_15)

        checkBox_3 = QtWidgets.QCheckBox(widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(checkBox_3.sizePolicy().hasHeightForWidth())
        checkBox_3.setSizePolicy(sizePolicy)
        checkBox_3.setMinimumSize(QtCore.QSize(50, 0))
        checkBox_3.setMaximumSize(QtCore.QSize(50, 16777215))
        checkBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        checkBox_3.setObjectName("checkbox")
        checkBox_3.clicked.connect(lambda x: self.on_widget_click(False, label_15, checkBox_3, widget_6))
        
        horizontalLayout.addWidget(checkBox_3)

        for i, value in enumerate(self.config['program']['key']):
            lineEdit_5 = QtWidgets.QLineEdit(widget_6)
            lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
            lineEdit_5.setStyleSheet("background-color: #EEEDEB;") 
            lineEdit_5.setMinimumSize(QtCore.QSize(100, 0))
            lineEdit_5.setMaximumSize(QtCore.QSize(100, 16777215))
            lineEdit_5.setObjectName(f"lineEdit_{i}")
            validator = NumberValidator()
            lineEdit_5.setValidator(validator)
            horizontalLayout.addWidget(lineEdit_5)
        
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        horizontalLayout.addItem(spacerItem1)

        layout.addLayout(horizontalLayout)

        line = QtWidgets.QFrame(widget_6)
        line.setFrameShape(QtWidgets.QFrame.HLine)
        line.setFrameShadow(QtWidgets.QFrame.Sunken)
        layout.addWidget(line)
        widget_6.mousePressEvent = lambda event: self.on_widget_click(True, label_15, checkBox_3, widget_6)
        widget_6.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        widget_6.customContextMenuRequested.connect(lambda pos: self.show_context_menu(pos, widget_6))
        self.verticalLayout_3.addWidget(widget_6)

    def delete_row(self, widget_6):
        self.verticalLayout_3.removeWidget(widget_6)
        label = widget_6.findChild(QtWidgets.QLabel, f"label_15")
        label.value = -1
        widget_6.deleteLater()
        self.change_label()
        self.set_value_label_select(label)

    def delete_all_row(self):
        widgets = self.scrollAreaWidgetContents.findChildren(QtWidgets.QWidget, QtCore.QRegExp("widget_6"))
        for widget in widgets:
            self.verticalLayout_3.removeWidget(widget)
            widget.deleteLater()
        self.number_stt = 0
        self.set_value_label_select(None)

    def change_label(self):
        labels = self.scrollAreaWidgetContents.findChildren(QtWidgets.QLabel, QtCore.QRegExp("label_15"))
        labels = [label for label in labels if label.value > 0]
        labels = sorted(labels, key=lambda x: x.value)
        self.number_stt = 0
        for label in labels:
            self.number_stt += 1
            label.setText(str(self.number_stt))
            label.value = self.number_stt
        #endregion
        #region xử lý menu table form 1
    def show_context_menu(self, pos, widget_6):
        context_menu = QMenu(self.scrollAreaWidgetContents)
        action3 = QAction(QIcon("icon/table-row-insert-512.webp"), "Add row", self.scrollAreaWidgetContents)
        action3.triggered.connect(lambda: self.add_row_value())
        context_menu.addAction(action3)

        action4 = QAction(QIcon("icon/2912590.png"), "Delete row", self.scrollAreaWidgetContents)
        context_menu.addAction(action4)
        action4.triggered.connect(lambda: self.delete_row(widget_6))

        action2 = QAction(QIcon("icon/table_delete-512.webp"), "Delete all", self.scrollAreaWidgetContents)
        action2.triggered.connect(self.delete_all_row)
        context_menu.addAction(action2)

        context_menu.exec_(self.scrollAreaWidgetContents.mapToGlobal(pos))
    
    def show_context_menu_sub(self, pos):
        context_menu = QMenu(self.tab)

        action3 = QAction(QIcon("icon/table-row-insert-512.webp"), "Add row", self.scrollAreaWidgetContents)
        action3.triggered.connect(lambda: self.add_row_value())
        context_menu.addAction(action3)

        action2 = QAction(QIcon("icon/table_delete-512.webp"), "Delete all", self.scrollAreaWidgetContents)
        action2.triggered.connect(self.delete_all_row)
        context_menu.addAction(action2)

        context_menu.exec_(self.scrollArea.mapToGlobal(pos))
        #endregion
        #region xử lý click row
    def on_widget_click(self, type, label_no, checkBox_3, widget):
        if type:
            checkBox_3.setChecked(not checkBox_3.isChecked())
        
        if checkBox_3.isChecked():
            widget.setStyleSheet("QWidget { background-color: #C3E2C2; }")
            self.set_value_label_select(label_no)
           
        else:
            widget.setStyleSheet("")
            self.set_value_label_select(None)
     
        self.processing_click_checkbox(checkBox_3)
        self.processing_color_widget(widget)
    
    def set_value_label_select(self, label):
        no = label.value if label is not None and label.value >0  else ''
        self.label_row_select.setText(f'Row Selected: {no}')
        self.label_row_select.value = label if label is not None and label.value >0 else None

    def processing_click_checkbox(self, checkBox_3):
        checkboxes = self.scrollAreaWidgetContents.findChildren(QtWidgets.QCheckBox, QtCore.QRegExp("checkbox.*"))
        for checkbox in checkboxes:
            if checkbox != checkBox_3:
                checkbox.setChecked(False)
    
    def processing_color_widget(self, widget):
        widgets = self.scrollAreaWidgetContents.findChildren(QtWidgets.QWidget, QtCore.QRegExp("widget_6"))
        for w in widgets:
            if widget != w:
                w.setStyleSheet("")  # Reset color
        #endregion
    #endregion

    #region form 2
    def load_params(self):
        self.clear_row_form2()
        label = self.comboBox_label2.currentText()
        if  label in self.config['cbr']:
            keys = self.config['cbr'][label]['feature_order']
            if keys is not None and len(keys)>0:
                for i, key in enumerate(keys):
                    self.add_key_value(i, key)
            self.add_key_value(-1, 'Cluster')
            
    def clear_row_form2(self):
        widgets = self.scrollAreaWidgetContents_3.findChildren(QtWidgets.QWidget, QtCore.QRegExp("widget_params"))
        for widget in widgets:
            lineEdit_3 = widget.findChild(QtWidgets.QLineEdit,  f"lineEdit_{widget.property('i')}")
            lineEdit_3.setObjectName('')
            self.verticalLayout_5.removeWidget(widget)
            widget.deleteLater()
    
    def add_key_value(self, i, key):
        widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents_3)
        widget_4.setObjectName("widget_params")
        widget_4.setProperty('i', i)
        horizontalLayout_7 = QtWidgets.QHBoxLayout(widget_4)
        horizontalLayout_7.setContentsMargins(0, 0, 0, 3)
        horizontalLayout_7.setObjectName("horizontalLayout_7")
        label_name = QtWidgets.QLabel(widget_4)
        label_name.setObjectName("label_name")
        label_name.setText(key.replace('_', ' ').title())
        horizontalLayout_7.addWidget(label_name)
        lineEdit_3 = QtWidgets.QLineEdit(widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(lineEdit_3.sizePolicy().hasHeightForWidth())
        lineEdit_3.setSizePolicy(sizePolicy)
        validator = NumberValidator()
        lineEdit_3.setValidator(validator)
        lineEdit_3.setObjectName(f'lineEdit_{i}')   
        if i == -1:
            lineEdit_3.setReadOnly(True)
            self.lineEdit_3 = lineEdit_3
        horizontalLayout_7.addWidget(lineEdit_3)
        self.verticalLayout_5.addWidget(widget_4)
        
    def procesing_data_form2(self):
        self.add_label_to_log_programs(text='Processing data...')
        widgets = self.scrollAreaWidgetContents_3.findChildren(QtWidgets.QWidget, QtCore.QRegExp("widget_params"))
        for i, widget in enumerate(widgets[:-1]):
            lineEdit = widget.findChildren(QtWidgets.QLineEdit, QtCore.QRegExp("lineEdit_.*"))[0]
            lineEditValue = lineEdit.text()
            if lineEditValue.strip() == '':
                lineEdit.setText('-999')
                label = widget.findChild(QtWidgets.QLabel, 'label_name').text()
                self.add_label_to_log_programs(text =f'Reset {label} value: -999')
           
        self.add_label_to_log_programs(type=0 ,  text='Processing completed!')
    
    def procesing_data_kn(self):
        if self.edt_k.text().strip() == "":
            self.edt_k.setText('400')
            self.add_label_to_log_programs(text =f'Reset K value: 400')
        if self.edt_n.text().strip() == "":
            self.edt_n.setText('5')
            self.add_label_to_log_programs(text =f'Reset N value: 5')
    
    def get_value_line_edit_form2(self):
        values = []
        label = self.comboBox_label2.currentText()
        if label in self.config['cbr']:
            for i, value in enumerate(self.config['cbr'][label]['feature_order']):
                lineEdit = self.scrollAreaWidgetContents_3.findChild(QtWidgets.QLineEdit, f"lineEdit_{i}")
                values.append(float(lineEdit.text()))
            return values
        return None
    
    def get_line_edit_form2(self):
        values = []
        label = self.comboBox_label2.currentText()
        if label in self.config['program']['data'] and label in self.config['program']['data']:
            for i, value in enumerate(self.config['cbr'][label]['feature_order']):
                lineEdit = self.scrollAreaWidgetContents_3.findChild(QtWidgets.QLineEdit, f"lineEdit_{i}")
                values.append(lineEdit)
            return values
        return None
         
    #endregion
    
    def add_label_to_log_programs(self, type =None, text = ''):
        color = 'black'
        if type == 0:
            color = 'green'
        elif type == 1:
            color = 'red'
        if text.strip() != '':
            label = QtWidgets.QLabel(text, self.log_programs)
            label.setStyleSheet(f"color: {color};")
            self.verticalLayout_9.addWidget(label)
    def format_number(self, num):
        if num.is_integer():
            return int(num)
        return num

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CBRChipCalc"))
        self.label_2.setText(_translate("MainWindow", "Path File"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Action"))
        self.label_row_select.setText(_translate("MainWindow", "Row Selected :"))
        self.btn_data_processing.setText(_translate("MainWindow", "Data Processing"))
        self.label_12.setText(_translate("MainWindow", "Label:"))
        self.comboBox_label.addItems(self.config['program']['data'])
        self.btn_autolabel.setText(_translate("MainWindow", "Auto label"))
        self.btn_calculate_12.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Home"))
        self.label.setText(_translate("MainWindow", "Type model"))
        self.groupBox.setTitle(_translate("MainWindow", "Parameter"))
        self.label_5.setText(_translate("MainWindow", "N:"))
        self.label_4.setText(_translate("MainWindow", "K:"))
        self.btn_calculate2.setText(_translate("MainWindow", "Calculate"))
        # self.label_6.setText(_translate("MainWindow", "KẾT QUẢ: 123"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "CBR"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Program Log"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Action"))
        self.btn_data_processing2.setText(_translate("MainWindow", "Data Processing"))
        self.btn_calculate2.setText(_translate("MainWindow", "Calculate"))

class NumberValidator(QtGui.QValidator):
    def validate(self, string, pos):
        # Check if the input string is empty, which is acceptable
        if string == "" or string =='-':
            return QtGui.QValidator.Acceptable, string, pos
        # Try to convert the string to a float
        try:
            float(string)
            return QtGui.QValidator.Acceptable, string, pos
        except ValueError as e:
            return QtGui.QValidator.Invalid, string, pos

    def fixup(self, input):
        # If the input is not valid, you can modify it here (e.g., strip non-numeric characters)
        return ''.join([ch for ch in input if ch in '0123456789.'])


