J:
  excel_file: excel\df_sheet_J_nna_nol_tp_dia.xlsx
  kmeans_model_path: src\models\kmean_J.joblib
  feature_order:  ['developpé', 'amorce', 'angle', 'diam_circle', 'eps', 'diameter', 'Qte']
  train_excel_path: excel/df_sheet_J_nna_nol_tp_dia_k_train.xlsx
  test_excel_path: excel/df_sheet_J_nna_nol_tp_dia_k_test.xlsx
OT:
  excel_file: excel\df_sheet_OT_nna_nol_tp_dia.xlsx
  kmeans_model_path: src\models\kmean_OT.joblib
  feature_order:  ['Qte', 'diameter', 'developpé', 'amorce', 'angle', 'long larg', 'eps', 'Dimension', 'long', 'larg', 'diam_circle']
  train_excel_path: excel/df_sheet_OT_nna_nol_tp_dia_k_train.xlsx
  test_excel_path: excel/df_sheet_OT_nna_nol_tp_dia_k_test.xlsx
'20':
  excel_file: excel\df_sheet_20_nna_nol_tp_dia.xlsx
  kmeans_model_path: src\models\kmean_20.joblib
  feature_order:  ['Qte', 'developpé', 'eps', 'angle', 'hauteur', 'diameter']
  train_excel_path: excel/df_sheet_20_nna_nol_tp_dia_k_train.xlsx
  test_excel_path: excel/df_sheet_20_nna_nol_tp_dia_k_test.xlsx
B:
  excel_file: excel\df_sheet_B_nna_nol_tp_dia.xlsx
  kmeans_model_path: src\models\kmean_B.joblib
  feature_order:  ['Qte', 'developpé', 'eps', 'angle', 'hauteur', 'diameter']
  train_excel_path: excel/df_sheet_B_nna_nol_tp_dia_k_train.xlsx
  test_excel_path: excel/df_sheet_B_nna_nol_tp_dia_k_test.xlsx
